### ISSUE TITLE
Unable to reset stream after calculating AWS4 signature

### ISSUE THREAD

**Issue by ankitpise** [Ghedeon/AwsInterceptor#8]
Occurs for POST method, GET methods are working fine though.
`@POST("getfixtures")
fun getFixtures(@Body fixturesRequestPOJO: FixturesRequestPOJO): Call<List<FixturePOJO>>`

`FATAL EXCEPTION: OkHttp Dispatcher
                                                                                   Process: net.test.app, PID: 22550
                                                                                   com.amazonaws.AmazonClientException: Unable to reset stream after calculating AWS4 signature
                                                                                       at com.amazonaws.auth.AWS4Signer.calculateContentHash(AWS4Signer.java:360)
                                                                                       at com.amazonaws.auth.AWS4Signer.sign(AWS4Signer.java:113)
                                                                                       at com.ghedeon.AwsInterceptor.sign(AwsInterceptor.java:72)
                                                                                       at com.ghedeon.AwsInterceptor.intercept(AwsInterceptor.java:53)
                                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                                    Caused by: java.io.IOException: Mark has been invalidated.
                                                                                       at java.io.BufferedInputStream.reset(BufferedInputStream.java:336)
                                                                                       at com.amazonaws.auth.AWS4Signer.calculateContentHash(AWS4Signer.java:358)
                                                                                       at com.amazonaws.auth.AWS4Signer.sign(AWS4Signer.java:113) 
                                                                                       at com.ghedeon.AwsInterceptor.sign(AwsInterceptor.java:72) 
                                                                                       at com.ghedeon.AwsInterceptor.intercept(AwsInterceptor.java:53) 
                                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                                       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) 
                                                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135) 
                                                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                       at java.lang.Thread.run(Thread.java:818) `

**Comment by Ghedeon** [comment]
@ankitpise Is the same for all of your devices/emulators? Just a guess but please, give a try to this snapshot build: https://jitpack.io/#Ghedeon/AwsInterceptor/bugfix~unable_to_reset_stream-SNAPSHOT

**Comment by sanztss** [comment]
Hey ankitpise, could you share your project so i can see how this awsinterceptor is implemented?

**Comment by ankitpise** [comment]
Structure is like
AWSInterceptor + Retrofit
API Gateway (IAM_AUTH) [Congito authentication]
Lambda

For now I am using GET instead of POST and template mapping of API gateway to deliver data to lambda, which is working out as quite good solution for me.

Is the same for all of your devices/emulators?
Yes

**Comment by connyhald** [comment]
I had the same issue. Using the SNAPSHOT release fixed it for me. Thanks.
